spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:foss_db}
    hikari:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    #database-platform: org.hibernate.dialect.MariaDB103Dialect
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

fcm :
    firebase_config_path : firebase/foss-eae04-firebase-adminsdk-fbsvc-a0577cfa14.json